export const englishMusicData = {
    album_probability: 0.7,
    single_label: 'Single',
    reviews: [
        'Absolute banger!',
        'This slaps so hard.',
        'On repeat all day.',
        'Instant classic.',
        'Chills every time I listen.',
        'Vibe check: PASSED.',
        'Production quality is insane.',
        'Vocals are heavenly.',
        'Underrated gem.',
        'This song saved my life.',
        'Fire track 🔥',
        "Can't get this melody out of my head.",
        'Masterpiece.',
        'Decent, but not their best work.',
        'Growing on me after a few listens.',
        'Getting major 80s vibes from this.',
        'Solid track, added to my library.',
        'Needs more bass.',
        'Lyrics are a bit cheesy, but the beat is good.',
        'Sounds like generic radio pop.',
        'Interesting mix of genres.',
        'Pretty chill background music.',
        'The bridge is the best part.',
        'My ears are bleeding.',
        'Total trash.',
        'Overproduced and soulless.',
        'Skipped immediately.',
        'Boring.',
        "I don't get the hype.",
        'Lyrics make zero sense.',
        'Sounds like everything else on the chart.',
        'Disappointed.',
        'Worst release of the year.',
        'Who let this get released?',
    ],
};
